// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CopyLineLink
{
    internal sealed partial class Vsix
    {
        public const string Id = "CopyLineLink.f4761d48-e6e7-4d8a-8b23-5280081c1ab4";
        public const string Name = "CopyLineLink";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Kevin Gliewe";
        public const string Tags = "";
    }
}
